# Generated by Django 6.0.4 on 2026-04-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cafe_logos/'),
        ),
    ]
