# Generated by Django 6.0.4 on 2026-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_cafe_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
