# Generated by Django 6.0.4 on 2026-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_feedback_is_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
