# Generated by Django 6.0.4 on 2026-05-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_cafe_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
