# Generated by Django 6.0.4 on 2026-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_cafe_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='consent_to_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
