# Generated by Django 6.0.4 on 2026-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_feedback_consent_to_contact_feedback_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ai_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_reply_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_reply_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_reply_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_urgency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
